In [45]:
import pandas as pd
import pprint

In [46]:
sample_df = pd.read_csv('sample_data_1000_8.csv')
sample_df =sample_df.rename(columns={'cand_id':'globalID'})
sample_df = sample_df.rename(columns={'ID':'cand_id'})
sample_df.head()

,Unnamed: 0,index,Unnamed: 0.1,candidate_name,candidate_surname,candidate_country,candidate_gender,c_address_latitude,c_address_longitude,ethnicity,type,url,globalID,fullname,cand_id
0,800,116524,116524,Hufrish,Damania,US,Other/Unknown,37.827178,-122.291308,Other/Multiracial,linkedin,https://www.linkedin.com/pub/hufrish-damania/9...,116524,HufrishDamania,800
1,801,138735,138735,Bonnie,Schmelz,US,Female,39.953187,-75.174967,White/Caucasian,linkedin,https://www.linkedin.com/in/bonnieschmelz,138735,BonnieSchmelz,801
2,802,119372,119372,Bruce,Batcheller,US,Male,37.774929,-122.419415,White/Caucasian,linkedin,https://www.linkedin.com/in/bruce-batcheller-6...,119372,BruceBatcheller,802
3,803,17003,17003,Bruno,ALMUDEVER,FR,Male,48.849920,2.637041,White/Caucasian,linkedin,https://www.linkedin.com/in/bruno-almudever-74...,17003,BrunoALMUDEVER,803
4,804,56295,56295,Kelvin,Ho,US,Male,37.774929,-122.419415,Asian,linkedin,https://www.linkedin.com/in/kelvinho,56295,KelvinHo,804

In [51]:
com_df = pd.read_csv('com_df.csv')
all_df = pd.merge(com_df,sample_df,on='cand_id',how='left')
compare_df = all_df[['cand_id', 'country','ethnicity','candidate_country']]
compare_df
compare_df.to_csv('compare_df_result.csv')

In [52]:
uni_df = pd.read_csv('university_df.csv')
all_df = pd.merge(uni_df,sample_df,on='cand_id',how='left')
compare_uni_df = all_df[['cand_id', 'country','ethnicity','candidate_country']]
compare_uni_df
compare_uni_df.to_csv('compare_uni_df_result.csv')

In [49]:
lang_df = pd.read_csv('language_df.csv')
lang_df

    Unnamed: 0  cand_id     name           proficiency
0            0    806.0  English   NATIVE_OR_BILINGUAL
1            0    809.0  English  PROFESSIONAL_WORKING
2            0    811.0  English     FULL_PROFESSIONAL
3            0    827.0  English     FULL_PROFESSIONAL
4            0    829.0  English  PROFESSIONAL_WORKING
5            0    837.0    Dutch   NATIVE_OR_BILINGUAL
6            0    842.0   Arabic   NATIVE_OR_BILINGUAL
7            0    845.0  Deutsch   NATIVE_OR_BILINGUAL
8            0    846.0  English     FULL_PROFESSIONAL
9            0    849.0  English     FULL_PROFESSIONAL
10           0    860.0  English     FULL_PROFESSIONAL
11           0    878.0  English   NATIVE_OR_BILINGUAL
12           0    880.0  English   NATIVE_OR_BILINGUAL
13           0    885.0  English   NATIVE_OR_BILINGUAL
14           0    889.0  English   NATIVE_OR_BILINGUAL
15           0    893.0  English   NATIVE_OR_BILINGUAL
16           0    894.0   French       LIMITED_WORKING
17           0    897.0  Chinese   NATIVE_OR_BILINGUAL
18           0    898.0  Chinese   NATIVE_OR_BILINGUAL

In [50]:
lang_df = pd.read_csv('language_df.csv')
all_df = pd.merge(lang_df,sample_df,on='cand_id',how='left')
compare_lang_df = all_df[['cand_id', 'name','proficiency','ethnicity','candidate_country']]
lang_Native_df = compare_lang_df.loc[compare_lang_df.proficiency == 'NATIVE_OR_BILINGUAL']
lang_Native_df

    cand_id     name          proficiency        ethnicity candidate_country
0     806.0  English  NATIVE_OR_BILINGUAL  White/Caucasian                US
5     837.0    Dutch  NATIVE_OR_BILINGUAL  White/Caucasian                US
6     842.0   Arabic  NATIVE_OR_BILINGUAL            Asian                IE
7     845.0  Deutsch  NATIVE_OR_BILINGUAL  White/Caucasian                AT
11    878.0  English  NATIVE_OR_BILINGUAL  White/Caucasian                US
12    880.0  English  NATIVE_OR_BILINGUAL  White/Caucasian                US
13    885.0  English  NATIVE_OR_BILINGUAL  White/Caucasian                US
14    889.0  English  NATIVE_OR_BILINGUAL            Asian                US
15    893.0  English  NATIVE_OR_BILINGUAL  White/Caucasian                US
17    897.0  Chinese  NATIVE_OR_BILINGUAL            Asian                US
18    898.0  Chinese  NATIVE_OR_BILINGUAL            Asian                US

## If 'proficiency' == 'NATIVE_OR_BILINGUAL' and name != English => Ethnicity